version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.2.8
  - dependency-name: next
    versions:
    - 10.1.3
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.2.8
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.24.0
